DEFAULT_WIZARD_STATE = '''{
    "items": {
        "gross farm receipts": {
            "value": null,
            "title": "Gross Farm Receipts",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.1135,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "receipts from crops": {
            "value": null,
            "title": "Receipts from crops",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.3324,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "receipts from livestock": {
            "value": null,
            "title": "Receipts from livestock",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.6479,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "receipts from direct payments": {
            "value": null,
            "title": "Receipts from direct payments",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0197,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms": {
            "value": null,
            "title": "Number of farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.078,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "acres of land": {
            "value": null,
            "title": "Acres of land",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.21,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "land owned (acres)": {
            "value": null,
            "title": "Land owned (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.166,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "land rented from gov (acres)": {
            "value": null,
            "title": "Land rented from gov (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.418,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "land rented from others (acres)": {
            "value": null,
            "title": "Land rented from others (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.109,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "crop share (acres)": {
            "value": null,
            "title": "Crop share (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.119,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "other land arrangements (acres)": {
            "value": null,
            "title": "Other land arrangements (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.081,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "farm size < 400 acres": {
            "value": null,
            "title": "Farm size < 400 acres",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.049,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "farm size (400-1599)": {
            "value": null,
            "title": "Farm size (400-1599)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.067,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "farm size (>1599)": {
            "value": null,
            "title": "Farm size (>1599)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.165,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total land": {
            "value": null,
            "title": "Total land",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.201,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "land in crops": {
            "value": null,
            "title": "Land in crops",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.122,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "summer fallow": {
            "value": null,
            "title": "Summer fallow",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.448,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "pasture (natural, tame & seeded)": {
            "value": null,
            "title": "Pasture (natural, tame & seeded)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.308,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "woodlands & wetlands": {
            "value": null,
            "title": "Woodlands & wetlands",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.03,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Land Use",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "farm capital": {
            "value": null,
            "title": "Farm capital",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": null,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "Ownership - sole proprietorship": {
            "value": null,
            "title": "Ownership - sole proprietorship",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.068,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": "operating",
            "name_keywords": ["sole"],
            "unit_of_measure": "Number of farms",
            "history": []
        },
        "Ownership - partnership": {
            "value": null,
            "title": "Ownership - partnership",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.058,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": "operating",
            "name_keywords": ["partnership"],
            "unit_of_measure": "Number of farms",
            "history": []
        },
        "Ownership - corporation": {
            "value": null,
            "title": "Ownership - corporation",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.115,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "Ownership - other": {
            "value": null,
            "title": "Ownership - other",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.205,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": "operating",
            "name_keywords": ["other"],
            "unit_of_measure": "Number of farms",
            "history": []
        },
        "total wheat (acres)": {
            "value": null,
            "title": "Total wheat (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.149,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["wheat,", "total"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "spring wheat (acres)": {
            "value": null,
            "title": "Spring wheat (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.093,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["spring", "wheat"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "durum wheat (acres)": {
            "value": null,
            "title": "Durum wheat (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.406,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["durum", "wheat"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "Winter wheat (acres)": {
            "value": null,
            "title": "Winter wheat (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.178,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["winter", "wheat"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "oats (acres)": {
            "value": null,
            "title": "Oats (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.088,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["oats"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "barley (acres)": {
            "value": null,
            "title": "Barley (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.064,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["barley"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "mixed grain (acres)": {
            "value": null,
            "title": "Mixed grains (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.114,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["mixed", "grains"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "corn for grain (acres)": {
            "value": null,
            "title": "Corn for grain (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.128,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["corn", "grain"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "buckwheat (acres)": {
            "value": null,
            "title": "Buckwheat (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["buckwheat"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "total rye (acres)": {
            "value": null,
            "title": "Total rye (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.347,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["rye,", "total"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "fall rye (acres)": {
            "value": null,
            "title": "Fall rye (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.17,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["fall", "rye"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "spring rye (acres)": {
            "value": null,
            "title": "Spring rye (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["spring", "rye"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "corn for silage (acres)": {
            "value": null,
            "title": "Corn for silage (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.091,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["corn", "silage"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "alfalfa (acres)": {
            "value": null,
            "title": "Alfalfa (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.149,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["alfalfa"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "other hay (acres)": {
            "value": null,
            "title": "Other hay (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.089,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["other", "hay"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "canola (acres)": {
            "value": null,
            "title": "Canola (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.046,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["canola"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "flaxseed (acres)": {
            "value": null,
            "title": "Flaxseed (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.206,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["flaxseed"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "soybeans (acres)": {
            "value": null,
            "title": "Soybeans (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.114,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["soybeans"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "mustard (acres)": {
            "value": null,
            "title": "Mustard (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.581,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["mustard"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "sunflower (acres)": {
            "value": null,
            "title": "Sunflower seed (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.297,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["sunflower"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "potato (acres)": {
            "value": null,
            "title": "Potato (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.114,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["potatoes"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "dry field peas (acres)": {
            "value": null,
            "title": "Dry field peas (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.147,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["dry", "field", "peas"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "lentils (acres)": {
            "value": null,
            "title": "Lentils (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.653,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["lentils"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "dry white beans (acres)": {
            "value": null,
            "title": "Dry white beans (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.193,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["dry", "white", "beans"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "other dry bean (acres)": {
            "value": null,
            "title": "Other dry bean (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.237,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["other", "dry", "beans"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "sugar beets (acres)": {
            "value": null,
            "title": "Sugar beets (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.032,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["sugar", "beets"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "triticale (acres)": {
            "value": null,
            "title": "Triticale (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.41,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["triticale"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "forage seed for seed (acres)": {
            "value": null,
            "title": "Forage seed for seed (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.294,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["forage", "seed"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "other field crops (acres)": {
            "value": null,
            "title": "Other field crops (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.445,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "crops",
            "name_keywords": ["other", "field", "crops"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "total fruits, berries, nuts (acres)": {
            "value": null,
            "title": "Total fruits, berries, nuts (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.01,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "strawberries (acres)": {
            "value": null,
            "title": "Strawberries (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.01,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "fruits",
            "name_keywords": ["strawberries"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "raspberries (acres)": {
            "value": null,
            "title": "Raspberries (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.025,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "fruits",
            "name_keywords": ["raspberries"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "number of greenhouses": {
            "value": null,
            "title": "Number of greenhouses",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.091,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["total", "greenhouse", "area"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "sq ft of greenhouse in use": {
            "value": null,
            "title": "Sq ft of greenhouse in use",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.457,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["total", "greenhouse", "area"],
            "unit_of_measure": "Square feet",
            "history": []
        },
        "number of flower greenhouses": {
            "value": null,
            "title": "Number of flower greenhouses",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.028,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["flower"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "sq ft of flower greenhouses": {
            "value": null,
            "title": "Sq ft of flower greenhouses",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["flower"],
            "unit_of_measure": "Square feet",
            "history": []
        },
        "number of vegetable greenhouses": {
            "value": null,
            "title": "Number of vegetable greenhouses",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.241,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["vegetable"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "sq ft of vegetable greenhouses": {
            "value": null,
            "title": "Sq ft of vegetable greenhouses",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Greenhouse Farming",
            "included": true,
            "file_keyword": "greenhouse",
            "name_keywords": ["vegetable"],
            "unit_of_measure": "Square feet",
            "history": []
        },
        "irrigation (acres)": {
            "value": null,
            "title": "Irrigation (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.313,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Crop Production",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["irrigation"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "commercial fertilizer": {
            "value": null,
            "title": "Commercial fertilizer (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.115,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Other",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["commercial", "fertilizer"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "herbicide": {
            "value": null,
            "title": "Herbicide (acres)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.127,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Other",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["herbicides"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "insecticide": {
            "value": null,
            "title": "Insecticide",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.127,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Other",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["insecticides"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "fungicide": {
            "value": null,
            "title": "Fungicide",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.113,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Other",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["fungicides"],
            "unit_of_measure": "Acres",
            "history": []
        },
        "number of farms using manure": {
            "value": null,
            "title": "Number of farms using manure",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.073,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Sustainability",
            "included": true,
            "file_keyword": "inputs",
            "name_keywords": ["manure", "applied"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "total hens and chickens": {
            "value": null,
            "title": "Total hens and chickens",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.072,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "broilers, roasters": {
            "value": null,
            "title": "Broilers, roasters",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "turkey": {
            "value": null,
            "title": "Turkey",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.0,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "table egg": {
            "value": null,
            "title": "Table egg (dozens)",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.039,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": "egg",
            "name_keywords": ["table"],
            "unit_of_measure": "Number of eggs (dozens)",
            "history": []
        },
        "number of farms broilers": {
            "value": null,
            "title": "Number of farms broilers",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.03,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms turkey": {
            "value": null,
            "title": "Number of farms turkey",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.023,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms table eggs": {
            "value": null,
            "title": "Number of farms table eggs",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.05,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": "egg",
            "name_keywords": ["table"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "total cows and calves": {
            "value": null,
            "title": "Total cows and calves",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.14,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "bulls": {
            "value": null,
            "title": "Bulls",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.16,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total cows": {
            "value": null,
            "title": "Total cows",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.156,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "dairy cows": {
            "value": null,
            "title": "Dairy cows",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.051,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "beef cows": {
            "value": null,
            "title": "Beef cows",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.118,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total pigs": {
            "value": null,
            "title": "Total pigs",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.026,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of pig farms": {
            "value": null,
            "title": "Number of pig farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.05,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total sheep and lambs": {
            "value": null,
            "title": "Total sheep and lambs",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.041,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of sheep farms": {
            "value": null,
            "title": "Number of sheep farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.049,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of horse farms": {
            "value": null,
            "title": "Number of horse farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.077,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": "type",
            "name_keywords": ["horse"],
            "unit_of_measure": "Number of farms",
            "history": []
        },
        "number of goat farms": {
            "value": null,
            "title": "Number of goat farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.062,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of bison farms": {
            "value": null,
            "title": "Number of bison farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.025,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of rabbit farms": {
            "value": null,
            "title": "Number of rabbit farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.064,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of head of llama": {
            "value": null,
            "title": "Number of head of llama",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.052,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "colonies of honeybees": {
            "value": null,
            "title": "Colonies of honeybees",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.093,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": "bees",
            "name_keywords": ["honeybees", "colonies"],
            "unit_of_measure": "Number",
            "history": []
        },
        "gallons of pollinating bees": {
            "value": null,
            "title": "Gallons of pollinating bees",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.341,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Livestock",
            "included": true,
            "file_keyword": "bees",
            "name_keywords": ["pollinating", "gallons"],
            "unit_of_measure": null,
            "history": []
        },
        "market value of farm capital": {
            "value": null,
            "title": "Market value of farm capital",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.109,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "market value of owned land and buildings": {
            "value": null,
            "title": "Market value of owned land and buildings",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.102,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "market value of rented land and buildings": {
            "value": null,
            "title": "Market value of rented land and buildings",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.116,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "market value of livestock and poultry": {
            "value": null,
            "title": "Market value of livestock and poultry",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.138,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total number of farms": { 
            "value": null,
            "title": "Total number of farms",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.049,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "dairy": {
            "value": null,
            "title": "Dairy",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.049,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "cattle": {
            "value": null,
            "title": "Cattle",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.107,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "hog": {
            "value": null,
            "title": "Hog",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.03,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "poultry": {
            "value": null,
            "title": "Poultry",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.019,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "sheep and goat": {
            "value": null,
            "title": "Sheep and goat",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.045,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "other livestock": {
            "value": null,
            "title": "Other livestock",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.037,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "wheat": {
            "value": null,
            "title": "Wheat",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.133,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "grain / oilseed": {
            "value": null,
            "title": "Grain / oilseed",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.066,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "hay": {
            "value": null,
            "title": "Hay",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.058,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "fruit / tree nut": {
            "value": null,
            "title": "Fruit / tree nut",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.029,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "vegetable/melon": {
            "value": null,
            "title": "Vegetable/melon",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.064,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "greenhouse": {
            "value": null,
            "title": "Greenhouse",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.068,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "other": {
            "value": null,
            "title": "Other",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.097,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Types of Farms",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "total paid labour": {
            "value": null,
            "title": "Total paid labour",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.111,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "paid labour family": {
            "value": null,
            "title": "Paid labour family",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.12,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "paid work full time, year round": {
            "value": null,
            "title": "Paid work full time, year round",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.163,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "paid work part time, year round": {
            "value": null,
            "title": "Paid work part time, year round",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.022,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "paid work seasonal": {
            "value": null,
            "title": "Paid work seasonal",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.079,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms reporting direct sales": {
            "value": null,
            "title": "Number of farms reporting direct sales",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.053,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms selling unprocessed products": {
            "value": null,
            "title": "Number of farms selling unprocessed products",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.05,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms selling value added products": {
            "value": null,
            "title": "Number of farms selling value added products",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.086,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with kiosks, upick, etc.": {
            "value": null,
            "title": "Number of farms with kiosks, upick, etc.",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.049,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms selling at farmers markets": {
            "value": null,
            "title": "Number of farms selling at farmers markets",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.066,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Revenue, Market Value, and Direct Sales",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with succession planning to: family members": {
            "value": null,
            "title": "Number of farms with succession planning to: family members",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.107,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": "succession",
            "name_keywords": ["family"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "number of farms with succession planning to: non-family members": {
            "value": null,
            "title": "Number of farms with succession planning to: non-family members",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.089,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": "succession",
            "name_keywords": ["non-family"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "number of farms with renewable energy": {
            "value": null,
            "title": "Number of farms with renewable energy",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.06,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Sustainability",
            "included": true,
            "file_keyword": "renewable",
            "name_keywords": ["production", "total"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "number of farms with solar panels": {
            "value": null,
            "title": "Number of farms with solar panels",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.063,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Sustainability",
            "included": true,
            "file_keyword": "renewable",
            "name_keywords": ["solar"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "number of farms with wind turbines": {
            "value": null,
            "title": "Number of farms with wind turbines",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.054,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Sustainability",
            "included": true,
            "file_keyword": "renewable",
            "name_keywords": ["wind"],
            "unit_of_measure": "Number of farms reporting",
            "history": []
        },
        "number of farm operators": {
            "value": null,
            "title": "Number of farm operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.077,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with one operator": {
            "value": null,
            "title": "Number of farms with one operator",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.079,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with 2 or more operators": {
            "value": null,
            "title": "Number of farms with 2 or more operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.075,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with male operators": {
            "value": null,
            "title": "Number of farms with male operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.079,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "number of farms with female operators": {
            "value": null,
            "title": "Number of farms with female operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": 0.072,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "average age of operators": {
            "value": null,
            "title": "Average age of operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": null,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        },
        "% of female farm operators": {
            "value": null,
            "title": "% of female farm operators",
            "description": "",
            "method": null,
            "date_value_was_applied": null,
            "ratio": null,
            "ratio_last_updated": null,
            "quality": null,
            "category": "Workforce",
            "included": true,
            "file_keyword": null,
            "name_keywords": [],
            "unit_of_measure": null,
            "history": []
        }
    },
    "meta": {
        "last_page": "IntroPage",
        "last_run": null
    }
}'''

def get_default_wizard_state():
    return DEFAULT_WIZARD_STATE